mrHoft/fpg-34
fastPaws-game/fastPaws pull request #10
Opened 2023-03-29 19:44 UTC by mrHoft

![image](https://user-images.githubusercontent.com/51874769/228646071-467efd78-5dd3-4611-918e-73a757c9bb4e.png)
Страница профиля.
Использован "react-hook-form".
Страница должна... будет... выполнять сразу 3 функции:
- показывать настройки профиля (закомментировано до момента подключения Store)
- менять профиль
- менять аватар

По событию submit пока просто выводит содержимое формы.
Проверяет валидность полей непосредственно перед сабмитом, выводит сообщения об ошибках.
Смена аватара пока не производится. Сделаю когда апи подтянем. Но при клике вызывает выбор файла и отрабатывает результат, выводя в консоль.

2023-03-31 09:33 UTC, bin-umar requested changes
В обязательном порядке жду от вас prettier-а, без него очень сложно ревьюит.

2023-03-31 09:33 UTC, bin-umar commented on packages/client/src/assets/icons/DefaultAvatar.tsx
Не советую svg-шки вручную делать React компонентами. Для этого есть готовые утилиты https://react-svgr.com/

2023-03-31 09:33 UTC, bin-umar commented on packages/client/src/components/ProfileAvatar.tsx
> +	background-image: url("data:image/svg+xml, %3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 256 256'%3E%3Crect width='256' height='256' fill='none'/%3E%3Cline x1='128' y1='192' x2='128' y2='22
Не очень хорошо впихнуть svg вручную в код, для этого необходимо использовать лоадеры всякие, вроде в Vite это должен быть автоматом, если нет, попробуйте https://www.npmjs.com/package/vite-svg-loader

2023-03-31 09:33 UTC, bin-umar commented on packages/client/src/assets/icons/DefaultAvatar.tsx
Или https://www.npmjs.com/package/vite-svg-loader

2023-03-31 09:33 UTC, bin-umar commented on packages/client/src/components/ProfileAvatar.tsx
В этой файле сильно нарушены отступы, вместо табов стоит  то ли 6, то ли 8 space. В названиях функции не хватает отступов. Советую прочитать https://learn.javascript.ru/coding-style , а также в обязательном порядке установить в проект prettier.

2023-03-31 09:33 UTC, bin-umar commented on packages/client/src/components/ProfileAvatar.tsx
> +	}
Вот например тут:
```suggestion
	const fileChoose = () => {
	    const node = fileUpload.current;
	    if (node) { 
	        node.click();
	    }
	}
```

2023-03-31 09:33 UTC, bin-umar commented on packages/client/src/components/ProfileForm.tsx
Тут также нарушены все виды отступов.

2023-03-31 09:33 UTC, bin-umar commented on packages/client/src/components/ProfileForm.tsx
> +				{...errors.first_name && {errorOn:true, errorMessage:'Name is incorrect'}}
Для чего тут вам нужен `spread` оператор?

2023-03-31 21:14 UTC, mrHoft commented on packages/client/src/components/ProfileAvatar.tsx
> +	}
И чем это лучше записи элементарного условия в одну строку?

2023-03-31 21:18 UTC, mrHoft commented on packages/client/src/components/ProfileAvatar.tsx
Мой IDE настроен на табы, поэтому нарушений нет.
> в обязательном порядке установить в проект prettier
Это решает проблему восприятия вполне "ровной" разметки в иных системах.

2023-03-31 21:23 UTC, mrHoft commented on packages/client/src/components/ProfileForm.tsx
> +				{...errors.first_name && {errorOn:true, errorMessage:'Name is incorrect'}}
Там нужно передать props а не object.

2023-04-01 07:32 UTC, bin-umar commented on packages/client/src/components/ProfileAvatar.tsx
Это командный проект, поэтому надо чтобы у всех был одинаковым.

2023-04-01 07:37 UTC, bin-umar commented on packages/client/src/components/ProfileAvatar.tsx
> +	}
Замечании было в основном не для однострочной строки, если вам так удобно, пишите. Но у тебя не соблюдены никак отступы. Вот например:
```ts
const fileChoose=()=>{
```
Надо чтобы:
```ts
const fileChoose = () =>{
```

2023-04-01 07:38 UTC, bin-umar commented on packages/client/src/components/ProfileAvatar.tsx
> +	}
Прочитай пожалуйста https://learn.javascript.ru/coding-style
![Screenshot 2023-04-01 at 10 37 41](https://user-images.githubusercontent.com/15624993/229272617-40f136e8-ce7e-4938-8d68-f8563c164414.png)

2023-04-01 07:39 UTC, bin-umar commented on packages/client/src/components/ProfileAvatar.tsx
> +	}
Возможно тебе кажется что это всё мелочи, но на командных и больших проектах без поддержки стиля код превращается в тыкву и будет сложночитаемым.

2023-04-01 07:40 UTC, bin-umar commented on packages/client/src/components/ProfileAvatar.tsx
> +	}
По поводу одной строки:
![Screenshot 2023-04-01 at 10 39 58](https://user-images.githubusercontent.com/15624993/229272756-317bc925-82b4-449e-bb2e-9ee3e4b58bb4.png)

2023-04-01 07:53 UTC, bin-umar approved these changes

2023-04-01 16:04 UTC, merged