Dyukovavictoria/fpg 20
fastPaws-game/fastPaws pull request #25
Opened 2023-04-06 12:43 UTC by ElPastel

Добавлен роутинг, частичная загрузка страниц, исправлен Layout на страницах профиля и лидерборда
![spinner2](https://user-images.githubusercontent.com/115109501/230381884-a27ecbe3-0a19-4cfb-abd3-60ce18de0e6b.PNG)

2023-04-06 17:26 UTC, mrHoft requested changes

2023-04-06 17:26 UTC, mrHoft commented on packages/client/src/constants/routes.ts
> +  GAME = '/game',
Предлагаю добавить роут MAIN='/main' (для MainPage) и вписать его в AuthForm.tsx
А роут GAME = '/game' использовать для страницы игры, на которую перенаправит кнопка в MainPage.

2023-04-06 17:26 UTC, mrHoft commented on packages/client/src/router.tsx
> +
Добавить страницу начала игры.

2023-04-06 17:26 UTC, mrHoft commented on packages/client/src/pages/PageWrapper.tsx
Красиво!
Стоило проработать дизайн.
А можно добавить надпись "Game is loading" и оставить до финальных доработок.

2023-04-06 17:28 UTC, mrHoft commented
Вик. Эти изменения нужно будет в sprint_2 делать.

2023-04-07 11:29 UTC, ElPastel commented on packages/client/src/components/ProfileForm.tsx
> +        <ProfileAvatar />
вынесла аватар из формы в компонент страницы

2023-04-07 11:32 UTC, ElPastel commented on packages/client/src/router.tsx
> +export const router = createBrowserRouter([
обернула весь роутер в suspens

2023-04-07 23:26 UTC, mrHoft approved these changes

2023-04-08 06:14 UTC, merged