Viktoria yakovleva/fpg 56
fastPaws-game/fastPaws pull request #36
Opened 2023-04-11 10:35 UTC by Vakulina

# Добавить Service Worker.
_**Service Worker работает только в продакшен сборке**_

## Реализована кастомная настройка  Service Workers без использования библиотек.
- Файл sw.js помещен в каталог public, т.к. необходимо, чтобы он попал в папку сборки ./dist без изменений (в дальнейшем я его читаю и трансформирую, записывая массив актуальных URL-адресов, в серверной среде средствами Node js). Типизировать данный файл не составит труда, однако я не смогла наладить компиляцию "на лету" sw.ts в sw.js для дальнейшей "ручной" обработки скриптом. Поэтому данный файл предлагаю пока оставить в формате js
- Настроено предварительное кэширование основных ресурсов (список хэшированных URL-адресов записывается в файл Service Worker скриптом ./src/getUrlList сразу после сборки проекта)
- Реализована стратегия **Сначала сеть, затем кэш**. Приложение попадает в кеш при первой загрузке и после этого может загружаться без интернета (не только элементы входа и пользовательские настройки, но и сама игра).

### [Предварительный деплой](https://fast-paws.onrender.com/game) для демонстрации работы в автономном режиме 

**//TODO** использовать  Workbox для создания полноценного PWA (с возможностью портирования в windows и на мобильные устройства)

### Скриншот
![image](https://user-images.githubusercontent.com/80524794/231098699-214f2fca-cf39-47ef-a1c9-75b722cfacd9.png)

2023-04-11 11:48 UTC, mrHoft approved these changes
Я ещё не добрался до соответствующего раздела теории поэтому просто ознакомился.
Approve потому что принимал участие в тестировании и убедился что это работает.

2023-04-13 06:50 UTC, bin-umar commented on packages/client/src/getUrlList.ts
> +  const newContent = content.replace("%HASHURLS%", JSON.stringify(urlList));
Лучше проверить error

2023-04-13 08:17 UTC, bin-umar requested changes

2023-04-13 08:17 UTC, bin-umar commented on packages/client/public/sw.js
Поредактируй, пожалуйста, команду линтера чтобы гонялся и по .js

2023-04-13 08:23 UTC, Vakulina commented on packages/client/public/sw.js
> +   if(!(event.request.url.startsWith('http'))) return;
Я не совсем поняла вопрос. Как раз-таки запросы от браузерных расширений НЕ начинаются с с http- их и отклоняем. Иначе, если включены некоторые расширения, то в консоли получаем ошибку "TypeError: Request scheme 'chrome-extension' is unsupported at sw.js"
https://stackoverflow.com/questions/49157622/service-worker-typeerror-when-opening-chrome-extension

2023-04-13 08:25 UTC, bin-umar commented on packages/client/public/sw.js
> +   if(!(event.request.url.startsWith('http'))) return;
Я почему-то не заметил `!`, извиняюсь)

2023-04-13 09:01 UTC, Vakulina commented on packages/client/public/sw.js
исправила

2023-04-13 09:02 UTC, Vakulina commented on packages/client/public/sw.js
> +        let responseClone = response.clone();
исправила здесь и у CACHE_ASSETS

2023-04-13 09:23 UTC, Vakulina commented on packages/client/src/getUrlList.ts
> +  const newContent = content.replace("%HASHURLS%", JSON.stringify(urlList));
добавила

2023-04-13 09:25 UTC, Vakulina commented on packages/client/tsconfig.json
> +  "include": ["src", "public"],
убрала. в итоге у меня в public только sw.js лежит

2023-04-13 10:14 UTC, mrHoft commented
Ознакомился.

2023-04-13 10:25 UTC, bin-umar approved these changes
Другое дело! Всё по красоте)

2023-04-13 10:25 UTC, bin-umar commented on packages/client/public/sw.js
> +  }
Можно не прописать err, если его не используешь 
```suggestion
  } catch {
    return []
  }
```

2023-04-13 10:25 UTC, bin-umar commented on packages/client/public/sw.js
> +  console.log('INSTALL')
Лучше наименовать 'SW INSTALL'

2023-04-13 10:28 UTC, bin-umar commented on packages/client/src/getUrlList.ts
> +  const newContent = content.replace("%HASHURLS%", JSON.stringify(urlList));
У тебя два error, один на `readFile`, другой на `writeFile`. Ты обрабатываешь только один. (всё ещё)

2023-04-14 14:32 UTC, merged