Dyukovavictoria/fpg 62
fastPaws-game/fastPaws pull request #37
Opened 2023-04-11 15:49 UTC by ElPastel

Добавлено движение фона

https://user-images.githubusercontent.com/115109501/231217696-03c3edf2-5ab8-49c2-8b4a-9a5655fa6648.mp4

2023-04-11 16:00 UTC, mrHoft commented on packages/client/src/engine/Engine.ts
В этом файле нет изменений. Более того, он устаревший. Я же просил сделать себе pull актуальной версии. Придётся дополнительный конфликт резолвить.

2023-04-11 16:01 UTC, mrHoft commented on packages/client/src/engine/ResourceLoader.ts
В этом файле нет изменений.
А должны быть, если бы ты грузила через него картинку.

2023-04-11 16:01 UTC, mrHoft commented on packages/client/src/engine/ResourceLoader.ts
В этом файле нет изменений.
А должны быть, если бы ты грузила через него картинку.

2023-04-11 16:02 UTC, mrHoft commented on packages/client/src/layers/ActionLayer.tsx
В этом файле нет изменений.

2023-04-11 16:04 UTC, mrHoft commented on packages/client/src/layouts/GameLayout.tsx
Тут результат работы prettier. Да: это я упустил :)

2023-04-11 16:08 UTC, mrHoft commented on packages/client/src/engine/BackgroundMotion.ts
> +  private timer: NodeJS.Timeout | undefined
Тут у тебя разве нет раздражающего подчёркивания, мол начальное значение для timer не задано в конструкторе?
Если есть и ты его просто проигнорировала то в телеграм я пояснял как это обойти.

2023-04-11 16:12 UTC, mrHoft commented on packages/client/src/engine/BackgroundMotion.ts
> +        this.img as CanvasImageSource,
Чтобы за зря не возиться с перетипизацией, можно было это сделать ещё в конструкторе.
Вместо:
this.img = ResourceLoader.sprite['background'] as HTMLImageElement
Сделать:
this.img = ResourceLoader.sprite['background'] as CanvasImageSource

2023-04-11 16:13 UTC, mrHoft commented on packages/client/src/engine/BackgroundMotion.ts
> +    this.ctx?.drawImage(this.img as CanvasImageSource, x, y, imgW, imgH)
Заодно и здесь можно было бы без "as" обойтись.

2023-04-11 16:15 UTC, mrHoft commented on packages/client/src/engine/BackgroundMotion.ts
> +
Ваще зачот!
А чтобы не биндить, draw можно было сделать стрелочной функцией. Но так тоже вполне изящно!

2023-04-11 16:19 UTC, mrHoft commented on packages/client/src/engine/ResourceLoader.ts
> +
Вообще не понял зачем этот метод. Можно было применить уже существующий loadImg.

2023-04-11 16:20 UTC, mrHoft commented on packages/client/src/engine/ResourceLoader.ts
> +      // console.log('Loaded img:', name) // url
Это устаревшая версия файла. Но не страшно: актуальная, вроде отличается как раз закомментированными логами, которые ты тоже убрала :)

2023-04-11 16:26 UTC, mrHoft commented on packages/client/src/engine/ResourceLoader.ts
>  export default Resource.get(tempCallback)
В целом, зачот! Круто что во всём разобралась!
Только там в начале класса есть константа, которую нужно увеличить на единичку (по количеству подгружаемых ресурсов).

2023-04-11 16:29 UTC, mrHoft commented on packages/client/src/layers/LandscapeLayer.tsx
> +    }
Это уже не актуальные строки, которые даже как подсказка не понадобятся, так как ты уже написала методы класса Background, которые выполняют эти действия.

2023-04-12 06:11 UTC, ElPastel commented on packages/client/src/engine/BackgroundMotion.ts
> +        this.img as CanvasImageSource,
так не работает, потому что далее я задаю для картинки свойства height и width, которых нет у CanvasImageSource

2023-04-12 06:20 UTC, ElPastel commented
Исправлены замечания, добавлено три отдельных слоя. У движущихся слоев отдельные движки, т.к. при использовании одного класса анимация работает некорректно

https://user-images.githubusercontent.com/115109501/231367915-3e64a289-5068-46fc-802b-a9ab724cbc6a.mp4

2023-04-12 07:26 UTC, mrHoft requested changes

2023-04-12 07:26 UTC, mrHoft commented on packages/client/src/assets/background/layer_1.png
Верни пожалуйста картинки слоёв в папку MistyMountains чтобы мы могли добавлять разные локации в игру.

2023-04-12 07:26 UTC, mrHoft commented on packages/client/src/engine/GroundMotion.ts
Ох. Ты сделала по классу на каждый слой... Зачем?
Просто заведи Array, в который сложи данные картинок. Что то типа:
```
layers=[
  {  // Первый слой
    img,
    height,
    width,
    ar,
    dx,
    x,
    y,
    clearX,
    clearY
  },
  {},  // Второй слой
  ...
]
```
А потом в методе draw меняй "x" и отрисовывай эти слои по итерации layers.forEach. Так ведь гораздо проще!!!

2023-04-12 07:26 UTC, mrHoft commented on packages/client/src/engine/GroundMotion.ts
> +    this.multiplier = canvas.width / this.img.width
Во первых: что за multiplier? Это слишком широкое понятие и оно не относится к картинке. У картинки есть соотношение сторон. Имена переменных это, по большей части, личный выбор, но хорошо когда оно само по себе даёт представление о том зачем эта переменная нужна. Используй пожалуйста название aspectRatio или просто ar.

canvas.width / this.img.width
Это не верно!!! Нужно:
img.height/this.img.width

2023-04-12 07:26 UTC, mrHoft commented on packages/client/src/engine/ResourceLoader.ts
> +      this.loadImg('layer1', layer1Url)
Сразу дай им имена типа "MistyMountains/layer1", чтоб когда у нас появятся новые локации у их слоёв были уникальные имена.

2023-04-12 07:26 UTC, mrHoft commented on packages/client/src/layers/ActionLayer.tsx
> +  z-index: 4;
Ужс! Ты сделала каждый слой фона как отдельный компонент?!!

2023-04-12 07:26 UTC, mrHoft commented on packages/client/src/layers/GroundLayer.tsx
Ужс! Ты сделала каждый слой фона как отдельный компонент!!!
У тебя должен быть один компонент заднего плана, с одним canvas и уже в нём рисуй разные слои одной картинки.

2023-04-12 07:26 UTC, mrHoft commented on packages/client/src/pages/GamePage.tsx
> +      <GroundLayer />
Вместо этих 3-х должен быть один компонент BackgroundLayer.

2023-04-12 07:34 UTC, mrHoft requested changes

2023-04-12 07:34 UTC, mrHoft commented on packages/client/src/layers/SkyLayer.tsx
> +    const multiplier = canvas.width / img.width
Вот тут у тебя размер поплыл. Выше писал что чтобы получить соотношение сторон нужно брать стороны одного объекта а не разных:
```img.height/ img.width```

2023-04-13 08:38 UTC, ElPastel commented on packages/client/src/assets/background/layer_1.png
они в current так и лежат в папочке, солью ветку с главной, поменяю пути и удалю картинки из своей ветки)

2023-04-13 09:27 UTC, mrHoft requested changes
Уже совсем близко! Ещё один маленький шажочек!

2023-04-13 09:27 UTC, mrHoft commented on packages/client/src/engine/BgMotion.ts
> +]
Ваще зачот!

2023-04-13 09:27 UTC, mrHoft commented on packages/client/src/engine/BgMotion.ts
> +    }
Вот умница! Синглтон по всем канонам!
Добавь сюда ещё проверку ctx, чтобы он не создавался если ctx пришёл null, на случай если BgMotion будет вызван откуда то кроме как из BackgroundLayer.

2023-04-13 09:27 UTC, mrHoft commented on packages/client/src/engine/BgMotion.ts
> +      const aspectRatio = canvas.width / img.width
```const aspectRatio = img.height / img.width```
Исправляй, проверяй. Ну сколько можно?!
Нельзя получить соотношение сторон сравнивая РАЗНЫЕ объекты!

2023-04-13 09:27 UTC, mrHoft commented on packages/client/src/engine/BgMotion.ts
> +      layerObj.imgH = img.height
Не нужно менять img.width и img.height оригинального объекта.
Пиши сразу в layerObj.imgW и layerObj.imgH.

2023-04-13 11:16 UTC, mrHoft approved these changes
Отлично!
Примени мелкую правку и давай уже на ревью отправлять!
Я тем временем дочитаю замечания в моём ПР чтобы сразу и у тебя исправить, если что.

2023-04-13 11:16 UTC, mrHoft commented on packages/client/src/engine/BgMotion.ts
> +      if (!ctx) return
```suggestion
  constructor(ctx?: CanvasRenderingContext2D) {
    if (!ctx) return
    if (BgMotion.__instance) {
```

2023-04-13 18:45 UTC, bin-umar commented
@mrHoft когда комментируешь чужой код, лучше избегать токсичных слов: _Ужс!_, _!!!_, _?!!_
Это не конструктивно и демотивирует человека и может обесценивать его работу.

2023-04-13 18:57 UTC, bin-umar approved these changes
Несмотря на то что всё ещё вижу чужие изменения в этом PR которые не касаются этой фичи, вижу что вы сами хорошо справились с ревью. И типы есть, и код читабельно написан. 👍

2023-04-13 18:57 UTC, bin-umar commented on packages/client/src/engine/BgMotion.ts
> +        )
В однострочных условиях ок прописать без скобок, но когда строки больше, всегда читабельнее со скобками:
```suggestion
      if (layer.x <= -canvas.width) {
         layer.x = 0
      }

      if (layer.x > -canvas.width) {
        this.ctx?.drawImage(
          layer.img as CanvasImageSource,
          canvas.width + layer.x,
          layer.y,
          layer.imgW,
          layer.imgH
        )
      }
```

2023-04-13 18:57 UTC, bin-umar commented on packages/client/src/engine/BgMotion.ts
> +  }
И да, Николай прав, чтобы избежать лишних байндингов, проще использовать стрелочные функции:
```suggestion
  public start = (speed: number = 20) => {
    if (!this.timer) {
      this.timer = setInterval(this.draw, speed)
    }
  }
```
Но, можно и так оставить

2023-04-13 18:57 UTC, bin-umar commented on packages/client/src/engine/BgMotion.ts
> +  private static __instance: BgMotion
Где-то с одним _, где-то с двумя. Для единообразия везде лучше делать одинаково

2023-04-13 19:59 UTC, merged