add some UI tests
fastPaws-game/fastPaws pull request #53
Opened 2023-04-18 12:09 UTC by Ilph

Добавил тесты на несколько UI (input и AuthForm). Есть незавершенные тесты, коммитить не стал, но они пропускаются.
С тестами на Engine еще не разобрался. Ругается на gift.js

2023-04-18 12:55 UTC, Vakulina requested changes
Ты решил не использовать react testing library которую советовал Алексей?
подтяни изменения из current и проверь тесты, пожалуйста. Были большие МР, в том числе я меняла все формы

2023-04-18 13:14 UTC, Ilph commented
> Ты решил не использовать react testing library которую советовал Алексей? подтяни изменения из current и проверь тесты, пожалуйста. Были большие МР, в том числе я меняла все формы

Нет, я использую именно react testing library. Я его его метод рендер переопределил просто в модуле teat-utils. @testing-library/user-event расширяет немного react testing library. Я уже подтянул изменения из current и все исправил. Интересно, почему опять конфликт, хотя эти файлы я резолвил. И почему в file chande попадают файлы которые я не трогал, может конечно из-за yarn format.

2023-04-18 23:15 UTC, mrHoft requested changes
Хорошее начало. Осталось систематизировать что из компонентов тестируем, а главное как тестируем. А использование снапшотов в нашем проекте, по моему мнению не применимо.
Руки прочь от gif.js! Если где то что то ругается то нужно верно сконфигурировать названия файлов чтобы тесты не запускались на том что не имеет расширения "test", к примеру.

2023-04-21 11:44 UTC, Ilph commented on packages/client/src/components/Game.tsx
> +      <AudioLayer />
Хорошо, уберу

2023-04-21 11:45 UTC, Ilph commented on packages/client/src/components/tests/__snapshots__/authForm.test.tsx.snap
> +        class="sc-fbJfA gxZABW"
Если не менять CSS правила, то и название класса не изменится.

2023-04-21 11:45 UTC, Ilph commented on packages/client/src/components/tests/authForm.test.tsx
> +        <AuthForm onSubmitFrom={handleSubmit} />
Для инпута есть

2023-04-21 11:49 UTC, Ilph commented on packages/client/src/components/tests/authForm.test.tsx
> +      const login = getByText('Пожалуйста, укажите корректный логин')
В данный момент этих констант нет. Если будет на этом постоянно падать, то тест можно будет пропустить

2023-04-21 11:50 UTC, Ilph commented on packages/client/src/modules/game/components/index.tsx
Почему тогда этот файл лежит в проекте?

2023-04-21 11:51 UTC, Ilph commented on packages/client/src/ui/input/input.test.tsx
> +    expect(tree).toMatchSnapshot()
Если не менять CSS правила, то и название класса не изменится.

2023-04-21 11:53 UTC, Ilph commented
Тесты запускаются только на файлах, которые имеют расширение test.{ts,tsx}

2023-04-21 11:54 UTC, Ilph commented
> Хорошее начало. Осталось систематизировать что из компонентов тестируем, а главное как тестируем. А использование снапшотов в нашем проекте, по моему мнению не применимо. Руки прочь от gif.js! Если где то что то ругается то нужно верно сконфигурировать названия файлов чтобы тесты не запускались на том что не имеет расширения "test", к примеру.

Тесты запускаются только на файлах, которые имеют расширение test.{ts,tsx}

2023-04-22 10:35 UTC, Vakulina commented on packages/client/src/components/tests/__snapshots__/authForm.test.tsx.snap
> +        class="sc-fbJfA gxZABW"
А если поменяем правила, то надо переписывать тест?

2023-04-22 10:36 UTC, Vakulina commented on packages/client/src/ui/input/input.test.tsx
> +    expect(tree).toMatchSnapshot()
Все-таки надо что-то придумать. Нельзя, чтобы тест зависил от правил. А ты проверял, как во время продакшен сборки происходит?

2023-04-23 13:14 UTC, Ilph commented on packages/client/src/ui/input/input.test.tsx
> +    expect(tree).toMatchSnapshot()
Суть snapshota в том, чтобы случайно никто не менял UI. Если намеренно меняешь UI, то запускаешь тест с флагом update, либо удаляешь snapshot и при новом запуске теста будет новый snapshot. Хорошо, я настрою так, чтоб эти тесты пропускались.

2023-04-26 07:16 UTC, mrHoft requested changes
FAIL  src/ui/input/input.test.tsx
FAIL  src/components/tests/authForm.test.tsx

2023-04-26 07:16 UTC, mrHoft commented on packages/client/src/ui/input/input.test.tsx
> +    expect(tree).toMatchSnapshot()
Про изменения: Вновь тестируем наличие слов в тексте формы... Текст может меняться.

2023-05-10 21:00 UTC, closed without merging