add leaderBoardApi
fastPaws-game/fastPaws pull request #64
Opened 2023-04-30 08:42 UTC by Ilph

Добавлен LiaderboardApi

![Снимок](https://user-images.githubusercontent.com/90051828/235343659-57fd260b-3196-40b9-8818-247da9a4257a.PNG)

Для меня пока не понятно как обновлять аватарку и количество набранных очков. В данный момент они берутся из начальных данных usera после добавления в leaderboard. Api обновления этих данных нет. Есть предположение, что надо подключать БД и брать эти данные из БД.

2023-04-30 15:09 UTC, Vakulina requested changes
Не совсем поняла, в чем проблема с аватаром? У нас к api лидерборда могут обращаться только защищенные пользователи, т.е. в стор обязательно будут лежать данные пользователя (и аватар в том числе, если есть)

Сейчас на самом деле есть проблема с тем, что результаты игры текущего юзера не сохраняются в лидербокс. Ты пытаешься это сделать на manePage, но это не правильно и вообще не работает. 

Предлагаю диспатчить addUserToLiderboard на странице с игрой:
-сначала отследить, что юзер авторизован (взять из стора)
-по завершении игры авторизованного юзера диспатчить  dispatch(addUserToLiderboard(user)) 
Тогда данные аватара тоже будут переданы в теле запроса, а потом мы их получим обратно в ответ на санку getTeamLiderboard. Внутри них будет лежать урл аватара.

Другой момент - не нужно на странице mainContent проверять авторизован пользователь или нет. У нас это делается на уровне роутов

2023-05-02 11:57 UTC, Ilph commented
123

2023-05-02 12:48 UTC, Ilph commented
> Не совсем поняла, в чем проблема с аватаром? У нас к api лидерборда могут обращаться только защищенные пользователи, т.е. в стор обязательно будут лежать данные пользователя (и аватар в том числе, если есть)
> 
> Сейчас на самом деле есть проблема с тем, что результаты игры текущего юзера не сохраняются в лидербокс. Ты пытаешься это сделать на manePage, но это, кажется, концептуально неправильным, да и не работает.
> 
> Предлагаю диспатчить addUserToLiderboard на странице с игрой: -сначала отследить, что юзер авторизован (взять из стора) -по завершении игры авторизованного юзера диспатчить dispatch(addUserToLiderboard(user)) Тогда данные аватара тоже будут переданы в теле запроса, а потом мы их получим обратно в ответ на санку getTeamLiderboard. Внутри них будет лежать урл аватара.
> 
> Другой момент - не нужно на странице mainContent проверять авторизован пользователь или нет. У нас это делается на уровне роутов
> 
> UPD запускала проект локально. Авторизовывалась. Играла в игру. И сама выходила и проигрывала - мои данные так и не попали в лидербокс.
> 
> UPD Собственно проблемы выше, озвученные тобой, возникают от того, что ты не нашел то место в нашем приложении, в котором следует диспатчить санку по сохранению данных пользователя в лидербокс

Логика работы с API Liaderboard ( не претендую на истинность своих рассуждений). Цель: получить на странице liderboard данные допустим 10 игроков( Имя, количество очков, аватарку).  Поэтому работать со стором не получится, так ка мы получим только данные текущего пользователя, а данные остальных игроков не будет. С получением данных по API(в смысле отправил запрос, получил ответ) проблем нет. 

Сложности возникают с добавлением данных юзера по API. **Как я понял добавлять usera по API liderboarda можно только один раз и изменению эти данные не подлежат.** Исходя из этого добавление юзера в liderboard я сделал после регистрации,  Если я правильно понял, как после регистрации, так и после авторизации мы попадаем на страницу mainContent. Поэтому dispatch(addUserToLiderboard(user)) сделал именно на этой странице. Здесь уже есть данные юзера из стор (но аватара еще нет). Не сделал на странице с игрой, так как игрок может до игры после регистрации пойти на страницу liderboarda.

На странице mainContent я проверяю успешно ли прошла регистрация или нет, что бы запрос на добавление usera отправлять только один раз после регистрации. Если использовать флаг isAuth только запрос будет отправляться каждый раз после авторизации, в нет нет необходимости. 

Твои данные и не должны были сохраниться. Так как запрос идет только после регистрации, а ты авторизуешься. Тут либо логику поменять на время, чтоб у всех появились данные в liderboard, либо на время кнопку поставить для отправки данных. 

Так как API liderboarda не позволяет менять данные, то пока не понятно как обновлять аватарку и набранные очки.

2023-05-02 12:51 UTC, Ilph commented on packages/client/src/api/LeaderboardApi.ts
> +    return FetchApi.post('/leaderboard', { body: JSON.stringify(data) })
Да, можно. В таком случае все api надо будет поменять

2023-05-02 13:04 UTC, Ilph commented on packages/client/src/store/leaderboard/LiaderboardActions.ts
> +export const getAllLeadearboard = createAsyncThunk(
эта ручка есть в сваггере. Я пытался играться с этой ручкой. Но сам до конца и не понял для чего нужен.

2023-05-02 13:07 UTC, Ilph commented on packages/client/src/utils/fetchApi.tsx
> +  static API_URL = baseApiConfigConnection.url
Константа baseApiConfigConnection уже была кем-то создана, я просто воспользовался. ОК, верну обратно.

2023-05-02 15:57 UTC, Vakulina commented on packages/client/src/components/MainContent.tsx
> +  const signUpStatus = useAppSelector(authSelectors.getSignUpStatus)
Тебе вообще не нужно проверять факт авторизации. Это защищенный роут. Проверка происходит в компоненте <RequireAuth >. На счет авторизации и регистрации вообще не поняла. У нас в системе нет отдельного статуса для зарегистрированного пользователя. Сразу после успешной регистрации юзер становится зарегистрированным (ориентируемся на флаг в сторе **isAuth**, но опять же - в лидерборде это отслеживать не нужно)

2023-05-02 16:00 UTC, Vakulina commented on packages/client/src/components/MainContent.tsx
> +      dispatch(addUserToLiderboard(body))
Игрок, который не авторизован, сможет поиграть в игру, но не сможет перейти на страницу лидербокса (ровно так, как это происходит сейчас).
Еще раз - я предлагаю СОХРАНЯТЬ данные в лидерборд dispatch(addUserToLiderboard(body)) в компоненте игры.
А получать данные лидербода логично на странице лидерборда.
_API не позволяет изменять данные._- это ты о каких данных?

2023-05-02 16:02 UTC, Vakulina commented on packages/client/src/components/MainContent.tsx
> +      dispatch(addUserToLiderboard(body))
Почему не на mainPage, потому что юзер может пройти по прямому урлу /game например или сразу /leaderboard

2023-05-02 16:04 UTC, Vakulina commented on packages/client/src/store/leaderboard/LiaderboardActions.ts
> +export const getAllLeadearboard = createAsyncThunk(
В свагерре я то видела, но в проекте она не используется и я тоже не поняла зачем она, вот и поинтересовалась

2023-05-02 16:06 UTC, Vakulina commented on packages/client/src/utils/fetchApi.tsx
> +  static API_URL = baseApiConfigConnection.url
знаешь, может быть и мной. просто глядя именно на твой компонент, я поняла, что меня смущает. Но это не критикал, я думаю

2023-05-02 16:15 UTC, Vakulina commented
> получить на странице liderboard данные допустим 10 игроков

Не поняла твой проблемы со стором. Нужны 10 юзеров в сторе- клади их туда пожалуйста, если надо. Я тебе нигде не предлагала ориентироваться на стор... Но я тебе не предлагала брать данные со стора. 
На странице лидербокса ты делаешь начальный запрос на данные 10 лидеров. Если лидербокс не открылся, то и запроса не будет (а не откроется он, если юзер не авторизован)
На странице с игрой (по завершении игры) ты делаешь запрос на сохранение (обновление) результатов юзера в лидербоксе с помощью апи (однозначно должен быть способ обновления данных, возможно, данные юзера, в т.ч. очки придется переписать заново). 
Если использовать флаг isAuth - то каждый раз будет отправлять запрос на получение данных 10 лидеров (и то только при открытии страницы лидербокса)

2023-05-02 16:24 UTC, Vakulina commented
> Исходя из этого добавление юзера в liderboard я сделал после регистрации, Если я правильно понял, как после регистрации, так и после авторизации мы попадаем на страницу mainContent. Поэтому dispatch(addUserToLiderboard(user)) сделал именно на этой странице. Здесь уже есть данные юзера из стор (но аватара еще нет). Не сделал на странице с игрой, так как игрок может до игры после регистрации пойти на страницу liderboarda.

Юзер может попасть на майнКонтент и не проходя авторизацию или регистрацию (просто сделав рефреш).  И вообще не поиграв в игру. Может и можно с этой страницы отправлять запрос- но зачем. Если нужно что-то сделать сразу после регистрации юзера и только в случае регистрации юзера - сделай это в сабмите формы регистрации (ну или где-то рядом, не в другом компоненте)

2023-05-02 16:28 UTC, Vakulina commented
> > Как я понял добавлять usera по API liderboarda можно только один раз и изменению эти данные не подлежат
> 
> Уточни, если это так, то пусть расскажут, как работать с апихой. Потому что юзер по логике любой игры будет играть много раз, стараясь улучшить свой результат

Прочитала твое предположение про апи.. ну хз, может быть, но тогда можно по апи вообще не передавать количество очком. Будем их в своей БД хранить.

2023-05-02 16:45 UTC, Vakulina commented
> Прочитала твое предположение про апи.. ну хз, может быть, но тогда можно по апи вообще не передавать количество очком. Будем их в своей БД хранить.
В текущий момент просто логика работы нашего лидербокса мне не ясна. Тебе точно нужно с ней разобраться и не гадать. Я все-таки поняла так, что в БД и свой сервер нам нужен для форма, а здесь только апишка яндекса

2023-05-02 17:06 UTC, Vakulina commented on packages/client/src/components/MainContent.tsx
> +  const signUpStatus = useAppSelector(authSelectors.getSignUpStatus)
@Ilph Еще момент, а как быть с юзерами, которые зарегистрировались в апи яндекса не через наше приложение? Мы же со своими паролями можем играть во все игры курса.

2023-05-02 17:39 UTC, Vakulina commented on packages/client/src/store/leaderboard/LiaderboardActions.ts
> +export const getAllLeadearboard = createAsyncThunk(
UPD судя по всему эта ручка позволяет делать сдвиг в массиве всех пользователей нашей игры, т.е. отображать не 10 лидеров, а всех участников рейтинга (используя пагинацию, например)

2023-05-09 11:05 UTC, mrHoft requested changes
Прошу прощения что в самом начале не увидел вашу с Викой переписку и не пояснил откуда и в какой момент брать score.
В итоге ты сам нашёл идеальное место: Game.tsx. Отлично что используешь метод return хука useEffect. В итоге, всякий раз когда пользователь покидает игру, в случае если он авторизован то производится обновление в лидерборде: молодчина!
Осталось навести порядок в этом хуке и тех данных, которыми он оперирует.

2023-05-09 12:39 UTC, Ilph commented on packages/client/src/components/Game.tsx
> +  newPoints.current = points
Попробую заменить на score

2023-05-09 12:46 UTC, Ilph commented on packages/client/src/utils/fetchApi.tsx
> +  public get: Request<null> = async (url: string, options = {}) => {
Я JSON.stringify у body перенес в fetchAPI. Поэтому на вход методы get, post и т.д могут получить body неизвестного типа.

2023-05-10 06:51 UTC, mrHoft requested changes

2023-05-10 06:51 UTC, mrHoft commented on packages/client/src/components/Game.tsx
> +  newPoints.current = score
Зачем ты объявляешь новые переменные? Используй существующую.

2023-05-10 06:54 UTC, mrHoft commented on packages/client/src/components/Game.tsx
> +    }
Не будет. Там же проверка стоит.

2023-05-10 07:24 UTC, mrHoft commented on packages/client/src/components/Game.tsx
> +  newPoints.current = score
score это и есть самое актуальное значение набранных очков. Просто отсылай эти данные при выходе из игры и всё.

Стоило бы сделать сравнение того что уже в лидерборде с текущим значением на случай если пользователь зашёл в игру и тут же вышел, то есть значение не поменялось, но учитывая что оно меняется каждые пару секунд геймплея, можно этого и не делать.

2023-05-10 08:34 UTC, mrHoft approved these changes

2023-05-10 13:34 UTC, Vakulina approved these changes
Нужно сразу решить конфликт с каррент, тем более конфликт не в служебных файлах, а в сторе и компонентах.

2023-05-10 13:36 UTC, Vakulina commented on packages/client/src/store/RootReducer.ts
>  import authSlice from './auth/AuthSlice'
и убери сравнения с null

2023-05-10 13:44 UTC, Vakulina commented on packages/client/src/store/RootReducer.ts
>  import authSlice from './auth/AuthSlice'
Понравилось упрощение FetchApi

2023-05-10 13:51 UTC, Vakulina approved these changes
Не работает сохранение в продакт сборке
можешь попробовать сам, убери   </React.StrictMode> из main - аналогичный эффект

2023-05-10 13:59 UTC, bin-umar commented on packages/client/src/utils/fetchApi.tsx
> +  public get: Request<null> = async (url: string, options = {}) => {
Почему бы не добавить generic?

2023-05-10 14:03 UTC, bin-umar commented on packages/client/src/components/Game.tsx
> +  newPoints.current = score
> Зачем ты объявляешь новые переменные? Используй существующую.

Да!

2023-05-10 14:04 UTC, bin-umar commented on packages/client/src/components/Game.tsx
> +    }
Что ты пытаешься делать в didMount?

2023-05-10 14:06 UTC, bin-umar commented on packages/client/src/constants/leaderBoard.ts
> +  TEAM_NAME: 'FastPaws',
Странное наименование, название самой константы должен быть заглавными буквами, а параметр наоборот, camelCase-ом
```suggestion
export const LEADERBOARD_CONSTS = {
  teamName: 'FastPaws',
```

2023-05-10 14:07 UTC, bin-umar commented on packages/client/src/models/LeaderBoardModel.ts
> +  name: string | undefined
```suggestion
  id?: number
  name?: string
```

2023-05-10 14:11 UTC, bin-umar commented on packages/client/src/utils/fetchApi.tsx
> +      body: body,
```suggestion
      body,
```

2023-05-10 14:15 UTC, bin-umar commented on packages/client/src/utils/fetchApi.tsx
> +  public get: Request<null> = async (url: string, options = {}) => {
Просто смущает само слово "null", тут получается так что тот кто вызывает этот метод, может в качестве options указать null, а в чём смысл? К тому ж это может привести к ошибке (ниже есть ...options)

2023-05-10 14:17 UTC, bin-umar commented on packages/client/src/utils/fetchApi.tsx
> +  public get: Request<null> = async (url: string, options = {}) => {
![Uploading Screenshot 2023-05-10 at 17.17.32.png…]()

2023-05-10 14:20 UTC, bin-umar commented on packages/client/src/store/leaderboard/LiaderboardActions.ts
> +      return
?

2023-05-10 16:23 UTC, Vakulina commented on packages/client/src/components/Game.tsx
> +    }
@bin-umar обращаю твое внимание, что в режиме разработки (или если убрать React.StrictMode) данные игры не сохраняются в лидербокс. Тут лучше @Ilph сам подскажет, почему ему пришлось пересохранять store  в useEffect между монтированием. И нужен совет, как поборот этот слайд-эффект

2023-05-10 18:01 UTC, Ilph commented on packages/client/src/components/Game.tsx
> +    }
Я пытаюсь при willUnmount отправить данные юзера и количество очков по API leaderborda,

2023-05-10 18:15 UTC, Ilph commented on packages/client/src/store/leaderboard/LiaderboardActions.ts
> +      return
Раскрой, пожалуйста, более детально вопрос. Я по неопытности не понял вопроса.

2023-05-10 18:17 UTC, Ilph commented on packages/client/src/modules/leaderBoardModule/PlayerItem.tsx
> +        <img src={avatarUrl != null ? `${fetchApi.getApiUrl()}/resources${avatarUrl}` : defaultAvatar} alt="" />
Убрал

2023-05-10 18:20 UTC, mrHoft commented on packages/client/src/components/Game.tsx
> +    }
То что приведено как контекст это unmount. Я поясню за Ильфата. Логика такая: когда мы выходим из игры (не важно: идём на главную страницу, в настройки, чат или лидерборд,- эти ссылки доступны из интерфейса игры) то производится запись набранных очков посредством addUserToLiderboard.

А вот что он делает в didMount мне тоже не понятно, да и смотрится это как то странно.

2023-05-10 18:26 UTC, mrHoft commented on packages/client/src/models/LeaderBoardModel.ts
> +export type TPlayerItemType = {
А ведь и вправду: у тебя и в начале T стоит и в конце "Type" добавлено. Можно выбрать что то одно.

2023-05-10 18:35 UTC, Ilph commented on packages/client/src/components/Game.tsx
> +  newPoints.current = score
без useRef значение score внутри useEffect теряется.

2023-05-10 18:38 UTC, Vakulina commented on packages/client/src/components/Game.tsx
> +    }
@mrHoft Ты попробовал в ПРОДАКШЕН режиме?

2023-05-10 18:39 UTC, Vakulina commented on packages/client/src/components/Game.tsx
> +    }
@bin-umar я имела ввиду ПРОДАКШЭН режим. В нем не сохраняются очки

2023-05-10 18:40 UTC, Vakulina commented on packages/client/src/components/Game.tsx
> +    }
Помоги, пожалуйста, что сделать, чтобы добиться синхронности данных?

2023-05-10 18:41 UTC, bin-umar commented on packages/client/src/components/Game.tsx
> +  newPoints.current = score
) Так тебе нужно просто его в dependency указать, useRef не нужен

2023-05-10 18:47 UTC, bin-umar commented on packages/client/src/models/LeaderBoardModel.ts
> +export type TPlayerItemType = {
> А ведь и вправду: у тебя и в начале T стоит и в конце "Type" добавлено. Можно выбрать что то одно.

Да, и я о том ж.

2023-05-10 20:33 UTC, Ilph commented on packages/client/src/components/Game.tsx
> +  newPoints.current = score
Если в dependency указать, то при каждом изменении очков будет запрос по API. А мне надо отправить запрос по API только один раз после того, как компонент размонтируется

2023-05-10 20:56 UTC, Ilph commented on packages/client/src/components/Game.tsx
> +    }
> Не работает сохранение в продакт сборке можешь попробовать сам, убери </React.StrictMode> из main - аналогичный эффект

Постараюсь описать то, что я заметил по поводу обновления данных в лидербоксе. Выводы справедливы как для Dev режима, так и для Prod. 
1. Игрок покидает страницу game. При этом по API лидербокса отправляется post запрос с данными юзера и набранными очками. По данным из вкладки Network данные отправляются всегда корректно.
2. При монтировании страницы лидербокса мы запрашиваем данные и отображаем. 
3. Если **НЕ** сразу переходить на страницу лидербокса, а допустим сначала посетить другие страницы и уже после загрузить страницу лидербокса, то данные обновляются всегда(раз 10 пробовал как в Prod так и в Dev).
4. Если после игры сразу перейти на страницу лидербокса, то данные могут либо обновиться, либо нет. POST запрос на обновление данных корректный, а вот ответ может  прийти со старыми данными. @bin-umar Отсюда вопрос: есть ли такая вероятность, что запрос на получение данных отрабатывает быстрее чем запрос на обновление? Если да, то как это можно правильно реализовать, чтоб данные приходили актуальные?

2023-05-10 20:58 UTC, Ilph commented on packages/client/src/utils/fetchApi.tsx
> +  public get: Request<null> = async (url: string, options = {}) => {
На что можно заменить? undefined?

2023-05-11 06:59 UTC, bin-umar commented on packages/client/src/components/Game.tsx
> +    }
Ребята, это какие-то хаки, так не должно быть (про useRef и didUnMount). Я постараюсь сегодня запустить у себя локально и посмотреть.

2023-05-11 12:16 UTC, bin-umar commented on packages/client/src/components/Game.tsx
> +    }
@Ilph @Vakulina @mrHoft я разобрался в вашей проблеме, проблема в том что обычно GameOver это когда закрывают игру, то есть нажимают кнопку Exit, ну и там же что-то показывают и отправляют запрос о score. У вас то ли специфика игры, то ли сами так решили что GameOver это когда пользователь обнуляется.

Но суть не в этом, что есть, то есть. Суть в том что когда закрывают игру (то есть выходят из игры, не важно через кнопку Exit, либо просто нажали на кнопки перехода в другие страницы), тогда и нужно отправлять запрос об обновление данных. У вас такое событие есть, в GamePause называется handleClose, но вы решили его использовать и при нажатии кнопки "Continue" что семантически неправильно. Но что более неправильно, в этот callback, вы передаёте `handleClose={handleContinue}`. Необходимо разделить handleClose и handleContinue в GamePause.tsx, и в Game.tsx сделать разные коллбеки. В handleClose нужно заложить как раз таки отправку запроса:
```ts
  const handleCloseGame = useCallback(() => {
    if (!isAuth || !user) {
      return;
    }

    const leaderBoardUpdate = getLeaderboarBody(user, score)
    dispatch(addUserToLiderboard(leaderBoardUpdate))
  }, [score])
```
Тогда у вас пропадают костыли с useRef и didUnMount-ом.

Вторая проблема, это то что апи лидерборда тупить, я покопал в истории, это известная проблема апи, к сожалению, пока не чинили. С ващей стороны отправляйте запросы в нужные места, всё.

2023-05-11 12:18 UTC, bin-umar requested changes
Везде надо исправить опечатки `Liderboard` => `Leaderboard` (везде board с маленькой буквой и L**ea**der), а также убрать костыли с useRef

2023-05-11 14:06 UTC, bin-umar commented on packages/client/src/utils/fetchApi.tsx
> +  public get: Request<null> = async (url: string, options = {}) => {
Да, undefined подошёл бы.

2023-05-11 14:07 UTC, bin-umar commented on packages/client/src/store/leaderboard/LiaderboardActions.ts
> +      return
@Ilph для чего там нужен return который ничего не делает?

2023-05-11 14:09 UTC, bin-umar commented on packages/client/src/store/leaderboard/LeaderboardSlice.ts
> +  addUserToLiderboardError: string | null
```suggestion
  addUserToLeaderboardStatus: RequestStatus
  addUserToLeaderboardError: string | null
```

2023-05-11 14:09 UTC, bin-umar commented on packages/client/src/store/leaderboard/LeaderboardSlice.ts
> +  addUserToLiderboardError: string | null
```suggestion
  addUserToLeaderBoardStatus: RequestStatus
  addUserToLeaderBoardError: string | null
```

2023-05-11 14:09 UTC, bin-umar commented on packages/client/src/store/leaderboard/LeaderboardSlice.ts
> +export type Tleaderboard = {
```suggestion
export type LeaderBoard = {
```

2023-05-11 14:10 UTC, bin-umar commented on packages/client/src/store/leaderboard/LiaderboardActions.ts
> +export const addUserToLiderboard = createAsyncThunk(
```suggestion
export const addUserToLeaderBoard = createAsyncThunk(
```

2023-05-11 14:10 UTC, bin-umar commented on packages/client/src/store/leaderboard/LiaderboardActions.ts
> +  async (body: TLeaderboardAddUser, { rejectWithValue }) => {
```suggestion
export const addUserToLeaderboard = createAsyncThunk(
  'leaderboard/addUserToLeaderboard',
  async (body: LeaderBoardAddUser, { rejectWithValue }) => {
```

2023-05-11 14:11 UTC, bin-umar commented on packages/client/src/store/leaderboard/LiaderboardActions.ts
> +  async (body: TLeaderboardRequest, { rejectWithValue }) => {
```suggestion
export const getTeamLeaderBoard = createAsyncThunk(
  'leaderboard/getTeamLeaderBoard',
  async (body: TLeaderBoardRequest, { rejectWithValue }) => {
```

2023-05-11 14:12 UTC, bin-umar commented on packages/client/src/store/leaderboard/LiaderboardActions.ts
> +      const response = await LeaderboardApi.getTeamLeaderboard(body, LEADERBOARD_CONSTS.teamName)
```suggestion
      const response = await LeaderBoardApi.getTeamLeaderBoard(body, LEADERBOARD_CONSTS.teamName)
```

2023-05-11 14:14 UTC, bin-umar commented on packages/client/src/utils/getLeaderboardBody.ts
> +const getLeaderboarBody = (user: TUser, score: number) => {
```suggestion
const getLeaderBoardBody = (user: TUser, score: number) => {
```

2023-05-11 21:42 UTC, bin-umar approved these changes

2023-05-11 22:06 UTC, Ilph commented
Вроде все пофиксил.
Еще один момент про useRef и willUnMount. Изначально, я тоже API повесил на handleClick. Но потом интуитивно показалось, что запрос лучше сделать при willUnMount, но для этого пришлось использовать useRef. Как я понял это получается костыль. Но я не совсем понимаю почему это костыль. Буду признателен, если сможешь уделить время и в двух словах объяснить

2023-05-12 07:21 UTC, merged

2023-05-12 08:29 UTC, bin-umar commented
> Но потом интуитивно показалось, что запрос лучше сделать при willUnMount.
Нет, не лучше. Само по себе это не запрещается, но в большинство случаев такие запросы делаются в конкретных действиях, а не в unMount-ах.

Использовать useRef не запрещено, но костыль был в том что ты дублировал значение score который уже есть в useState. В добавок к нему ещё какой-то useRef, чтобы сохранить значение isMounted, но зачем, не понятно. Должен быть один источник правды.