Настроить Redux и Router в SSR.
fastPaws-game/fastPaws pull request #66
Opened 2023-05-08 16:12 UTC by MSolomahin

### Какую задачу решаем
Добавлен роутер и редакс в SSR

2023-05-08 16:37 UTC, Vakulina commented on packages/client/src/router/index.tsx
> +      {routes.map(route => {
Буду иметь ввиду такой подход для больших приложений!

2023-05-08 19:17 UTC, Vakulina approved these changes

2023-05-08 20:00 UTC, bin-umar requested changes
В целом код написан в прекрасном виде! Проще не скидывать лишние изменения которые не связаны с текущей задачой.

2023-05-08 20:07 UTC, Vakulina commented on packages/client/ssr.tsx
> +export async function render(url: string, repository: UserRepository) {
Я не понимаю, что остается под мою задачу с initialStore..

2023-05-09 11:17 UTC, MSolomahin commented on packages/client/package.json
> +    "history": "^5.3.0",
Видимо да, не смог из него нужное достать. Но этот пакет забыл убрать пока пробовал разные подходы. Уберу

2023-05-09 11:17 UTC, mrHoft commented on packages/client/src/store/game/GameProgress.ts
Это временное решение, чтобы другой член команды смог приступить к своей задаче. А методы этого модуля пока не вписываются в новую концепцию взаимодействия с хранилищем. Мы решили переписать это когда будут решены все задачи, связанные с SSR.

2023-05-09 16:23 UTC, bin-umar commented on packages/client/src/router/routes.tsx
> +    path: 'game',
Почему его нет в Routes?

2023-05-09 16:25 UTC, bin-umar approved these changes

2023-05-10 12:43 UTC, merged