Dyukovavictoria/fpg 85
fastPaws-game/fastPaws pull request #76
Opened 2023-05-21 10:26 UTC by ElPastel

Реализован API форума с помощью PostgreSQL и Sequelize. Ручки описаны в README. Добавлена защита от некоторых уязвимостей helmet.

Как запустить:

т.к. окружение еще не настроено, необходимо локально установить postgres.
Затем в SQL Shell необходимо войти с username: postgres и паролем, выбранным в время установки postgres.
Далее вводим команды:
create database {name};
\connect {name};
В папку server кладем файл .env и задаем там свой пароль и название базы
Запускаем yarn bootstrap и yarn dev
Пример запроса: localhost:3001/api/v1/topics/1

2023-05-21 11:47 UTC, Ilph approved these changes

2023-05-21 19:08 UTC, mrHoft approved these changes
Отдельное спасибо за `controllers/README.md`

2023-05-21 20:02 UTC, bin-umar requested changes
Очень понравился декомопизация кода по палочкам, респект!)

Удали, пожалуйста, изменения связанные с CSP. 

Также для информации, обычно в реальных проектах между контроллером и моделем есть как минимум ещё один слой (одна абстракция), и не очень круто прямая связь между ними, но так как у вас логики очень мало и нечего усложнять то можно и так.

2023-05-21 20:04 UTC, bin-umar commented on packages/server/src/controllers/topicsController.ts
> +        ...req.body,
не советую так делать, тем более что у вас нет тайпингов (хотя они не спасут от лишнего количество полей которые из клиента могут скинуть в body), и нет понимания что может прилететь в request.body.
Лучше каждое поле отдельно указывать

2023-05-23 08:12 UTC, ElPastel commented on packages/server/package.json
> +    "reflect-metadata": "^0.1.13",
Это пакет для работы sequelize-typescript, в документации написано, что его необходимо установить дополнительно

2023-05-23 08:12 UTC, ElPastel commented on packages/server/index.ts
> +    })
Удалила

2023-05-23 08:12 UTC, ElPastel commented on packages/server/src/models/topicModel.ts
> +  override id: number | undefined
Например при создании новой строки в таблице методом create:
    ForumModel.create({ title: 'New Games' })
Нашла в документации sequelize более лаконичный вариант:
  declare id: number

2023-05-23 08:12 UTC, ElPastel commented on packages/server/src/models/forumModel.ts
> +  @Length({ min: 3, max: 120 })
Вообще если не проходит валидация, то  sequelize не создает вообще эту строку в бд и выбрасывает ошибку  SequelizeUniqueConstraintError, которая попадает в catch. Но я уберу, потому что конкретно в этой таблице это вообще не нужно, т.к. мы сами эти строки инициализируем при запуске приложения.

2023-05-23 08:13 UTC, ElPastel commented on packages/server/src/controllers/topicsController.ts
> +      await TopicModel.update({ title, content }, { where: { id: topic?.id } })
исправила

2023-05-23 08:14 UTC, ElPastel commented on packages/server/src/controllers/topicsController.ts
> +        ...req.body,
прописала все поля отдельно

2023-05-23 08:18 UTC, ElPastel commented on packages/server/src/controllers/commentsController.ts
> +      }
В sequalize как раз все оказалось просто и интуитивно понятно, а вот сама я пока не смогла написать)) не хотелось бы задерживать других членов команды, так как их задачи зависят от моей, попробую после апрува спокойно сесть и разобраться)

2023-05-23 08:18 UTC, ElPastel commented on packages/server/src/controllers/topicsController.ts
> +  async createTopic(req: Request, res: Response) {
постараюсь добавить в следующих задачах

2023-05-23 08:46 UTC, bin-umar commented on packages/server/index.ts
> +  app.use(helmet())
helmet как раз таки для CSP и был нужен, не?

2023-05-23 08:48 UTC, bin-umar commented on packages/server/src/controllers/commentsController.ts
> +      if (!commentId) {
Я наоборот писал что такой вариант немного излишний, извини за misunderstanding))
```suggestion
      const { id } = req.params

      if (!Number(id)) {
```

2023-05-23 08:55 UTC, bin-umar commented on packages/server/src/controllers/commentsController.ts
> +      if (!commentId) {
Конкретно в таком примере проблема в использование [?? Nullish_coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) 

Он нужен как раз в ситуации когда нам не нужны значения `null` или `undefined` в выражение слева от него. А в твоём случае результатом `Number(req.params.id)` никогда не будет `null` или `undefined`
<img width="756" alt="Screenshot 2023-05-23 at 11 52 39" src="https://github.com/fastPaws-game/fastPaws/assets/15624993/e86aa400-5940-4620-b088-313f1173b9c7">
Соответственно выражение `?? null` бессмысленное и никогда не будет достигнуть.

Но даже если допустим что конструктор `Number` может вернуть null, то в чём смысл его избежать и дать ему снова такое ж значение?)

2023-05-23 09:25 UTC, ElPastel commented on packages/server/index.ts
> +  app.use(helmet())
Просто в бэклоге видимо дублируются задания))) защиту просят добавить и в этом спринте, и в 9. Удалила!

2023-05-23 09:26 UTC, bin-umar commented on packages/server/package.json
> +    "helmet": "^7.0.0",
а отсюда? 😁

2023-05-23 09:26 UTC, bin-umar approved these changes

2023-05-23 09:27 UTC, ElPastel commented on packages/server/package.json
> +    "helmet": "^7.0.0",
все равно пригодится потом😁 сейчас удалю))

2023-05-23 09:33 UTC, merged