Solomahinmaxim/fpg 92
fastPaws-game/fastPaws pull request #79
Opened 2023-05-24 20:19 UTC by MSolomahin

### Какую задачу решаем
Добавил api форума на клиенте

2023-05-25 22:49 UTC, Vakulina requested changes
Честно говоря, результат не понятен. Развернула current локально (с твои последним МР). Не отобраается список форумов. Топики не добавляются. Запросы к серверу не уходят. Проверь работу своих экшенов, пожалуйста.

2023-05-26 08:16 UTC, bin-umar approved these changes
Топ!

2023-05-26 08:16 UTC, bin-umar commented on packages/client/src/utils/fetchApi.tsx
> +    return await baseFetch(url, METHODS.POST, options.body)
Нет необходимости написать return await, достаточно проще:
```suggestion
  public post: Request = async (url: string, options = {}) => {
    return baseFetch(url, METHODS.POST, options.body)
```
Подробнее можешь тут прочитать https://eslint.org/docs/latest/rules/no-return-await

2023-05-26 08:16 UTC, bin-umar commented on packages/client/src/utils/fetchApi.tsx
> +    return Promise.reject(result.reason)
Теоретически если try/catch выше выполниться catch, при этом response.ok будет false, то result будет undefined.

2023-05-27 09:42 UTC, Vakulina approved these changes
Хотелось бы все-таки понять, почему у меня не проходят запросы и увидеть, как это все вместе работает

2023-05-27 11:18 UTC, Vakulina commented on packages/client/src/api/UserApi.ts
> +    return FetchApi.put<TUser>('/user/profile/avatar', { body })
Перестало работать изменение аватара

2023-05-27 17:50 UTC, bin-umar commented
> Хотелось бы все-таки понять, почему у меня не проходят запросы и увидеть, как это все вместе работает

@Vakulina Посмотри тред этого PR-а в пачке. Задача по подключению экшнов к интерфейсу это отдельная задача, в этот входит только добавление нужных endpoint-ов и store.

2023-06-01 10:10 UTC, merged